[package]
name = "rayer"
version = "0.1.0"
authors = ["Timo von Holtz <tvh@tvholtz.de>"]

[dependencies]
decorum = "0.0.8"
euclid = "0.16.4"
rand = "0.4"
image = "0.18.0"
clap = "2.29.2"
num-traits = "0.1.42"
palette = { git = "https://github.com/Ogeon/palette.git", rev = "c5114e5" }
