[package]
name = "rayer"
version = "0.1.0"
authors = ["Timo von Holtz <vonholtz@cp-med.com>"]

[dependencies]
euclid = "0.16.4"
image = "0.18.0"
clap = "2.29.2"
num-traits = "0.1.42"
palette = "0.2.1"
